import Head from 'next/head'
import { useState } from 'react'


export default function Home() {
  const [count,setCount] = useState(0)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <center >
             <b> <h1> Counter </h1> </b>
                 <b> <span> {count} </span> </b>
          <button  onClick={()=>  setCount(count+1)} ><b>  + </b></button>
          <button  onClick={()=> setCount(count-1)}><b>  - </b></button>
      </center>

    </>
  )
}
